version: '3.1'

services:
   db:
     image: mysql:5.7
     ports:
      - "3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:php7.4
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: wpjb_
       WORDPRESS_DEBUG: false
     working_dir: /var/www/html
     volumes:
      - ./wp-content:/var/www/html/wp-content
      - .htaccess:/var/www/html/.htaccess
volumes:
    db_data: {}