<?php

register_post_type( 'crb_member', array(
	'labels' => array(
		'name'               => __( 'Team Members', 'crb' ),
		'singular_name'      => __( 'Member', 'crb' ),
		'add_new'            => __( 'Add New', 'crb' ),
		'add_new_item'       => __( 'Add new Member', 'crb' ),
		'view_item'          => __( 'View Member', 'crb' ),
		'edit_item'          => __( 'Edit Member', 'crb' ),
		'new_item'           => __( 'New Member', 'crb' ),
		'view_item'          => __( 'View Member', 'crb' ),
		'search_items'       => __( 'Search Team Members', 'crb' ),
		'not_found'          => __( 'No Team Members found', 'crb' ),
		'not_found_in_trash' => __( 'No Team Members found in trash', 'crb' ),
	),
	'public'              => true,
	'exclude_from_search' => false,
	'show_ui'             => true,
	'capability_type'     => 'post',
	'hierarchical'        => false,
	'_edit_link'          => 'post.php?post=%d',
	'query_var'           => true,
	'rewrite'             => array(
		'slug'       => 'member',
		'with_front' => false,
	),
	'menu_icon'           => 'dashicons-groups',
	'supports'            => array( 'title', 'editor', 'page-attributes', 'thumbnail' ),
));

register_post_type( 'crb_testimonial', array(
	'labels' => array(
		'name'               => __( 'Testimonials', 'crb' ),
		'singular_name'      => __( 'Testimonial', 'crb' ),
		'add_new'            => __( 'Add New', 'crb' ),
		'add_new_item'       => __( 'Add new Testimonial', 'crb' ),
		'view_item'          => __( 'View Testimonial', 'crb' ),
		'edit_item'          => __( 'Edit Testimonial', 'crb' ),
		'new_item'           => __( 'New Testimonial', 'crb' ),
		'view_item'          => __( 'View Testimonial', 'crb' ),
		'search_items'       => __( 'Search Testimonials', 'crb' ),
		'not_found'          => __( 'No Testimonials found', 'crb' ),
		'not_found_in_trash' => __( 'No Testimonials found in trash', 'crb' ),
	),
	'public'              => false,
	'exclude_from_search' => false,
	'show_ui'             => true,
	'capability_type'     => 'post',
	'hierarchical'        => false,
	'_edit_link'          => 'post.php?post=%d',
	'query_var'           => true,
	'menu_icon'           => 'dashicons-heart',
	'supports'            => array( 'title', 'editor', 'page-attributes'),
));

register_post_type( 'crb_property', array(
	'labels' => array(
		'name'               => __( 'Properties', 'crb' ),
		'singular_name'      => __( 'Property', 'crb' ),
		'add_new'            => __( 'Add New', 'crb' ),
		'add_new_item'       => __( 'Add new Property', 'crb' ),
		'view_item'          => __( 'View Property', 'crb' ),
		'edit_item'          => __( 'Edit Property', 'crb' ),
		'new_item'           => __( 'New Property', 'crb' ),
		'view_item'          => __( 'View Property', 'crb' ),
		'search_items'       => __( 'Search Properties', 'crb' ),
		'not_found'          => __( 'No Properties found', 'crb' ),
		'not_found_in_trash' => __( 'No Properties found in trash', 'crb' ),
	),
	'public'              => true,
	'exclude_from_search' => false,
	'show_ui'             => true,
	'capability_type'     => 'post',
	'hierarchical'        => false,
	'_edit_link'          => 'post.php?post=%d',
	'query_var'           => true,
	'rewrite'             => array(
		'slug'       => 'property',
		'with_front' => false,
	),
	'menu_icon'           => 'dashicons-admin-home',
	'supports'            => array( 'title', 'editor', 'page-attributes', 'thumbnail'),
));

register_post_type( 'crb_gallery', array(
	'labels' => array(
		'name'               => __( 'Portfolio', 'crb' ),
		'singular_name'      => __( 'Gallery', 'crb' ),
		'add_new'            => __( 'Add New', 'crb' ),
		'add_new_item'       => __( 'Add New Gallery', 'crb' ),
		'view_item'          => __( 'View Gallery', 'crb' ),
		'edit_item'          => __( 'Edit Gallery', 'crb' ),
		'new_item'           => __( 'New Gallery', 'crb' ),
		'view_item'          => __( 'View Gallery', 'crb' ),
		'search_items'       => __( 'Search Galleries', 'crb' ),
		'not_found'          => __( 'No Galleries found', 'crb' ),
		'not_found_in_trash' => __( 'No Galleries found in trash', 'crb' ),
	),
	'public'              => true,
	'exclude_from_search' => false,
	'show_ui'             => true,
	'capability_type'     => 'post',
	'hierarchical'        => false,
	'_edit_link'          => 'post.php?post=%d',
	'query_var'           => true,
	'rewrite'             => array(
		'slug'       => 'portfolio',
		'with_front' => false,
	),
	'menu_icon'           => 'dashicons-format-gallery',
	'supports'            => array( 'title','thumbnail' ),
));